### PR TITLE
added constants for w/2.0 i2c integration

### PR DESCRIPTION
**Pull request by kfirmanty**
Hi,

I have added the constants needed by this PR for teletype: https://github.com/monome/teletype/pull/211

### CODE REVIEW

**Comment by scanner-darkly** [comment]
are there plans to support up to 9 w/ devices?

**Comment by kfirmanty** [comment]
> are there plans to support up to 9 w/ devices?

I picked up these from PR for crow, and given that w/ can be in 3 independent modes then maybe it would be better to treat it as 3 different devices?

**Comment by scanner-darkly** [comment]
could you point me to the PR? iiuc, you can only have 1 mode at a time, so all 3 modes could share the same address, but i might be missing something.

the reason i ask is because the address space is limited and having 9 w/s seems like a pretty extreme edge case :)

**Comment by tehn** [comment]
sorry, i admit i was confused by this but thought i was misunderstanding

pinging @trentgill

**Comment by kfirmanty** [comment]
https://github.com/monome/crow/pull/342/files#diff-3771b69bf4c704869b6b65b24dbdefb0R4 for example here are two addresses reserved only for delay mode. But I must admit I also went overboard and assigned `0x73, 0x74, 0x75` to W/ which are not mentioned on that PR so sorry - my bad. I probably assumed that as the case with Telexo the whole `0xX0-9` space will be assigned to one device type, but instead of making assumptions I should probably just ask about it.

**Comment by scanner-darkly** [comment]
yeah, looks like 2 addresses for each mode, and different addresses for different modes, so 6 in total.

curious if there is a specific reason for using different addresses for different modes - ansible does that, which makes it difficult to created universal commands that are shared by all the modes (like, say, "get current mode") - separate addresses means the leader device would need to poll each address (this is what @csboling did for generic ansible teletype ops, each sends 3 requests to 3 different addresses). on the other hand, if they all share the same address, there is a potential issue if you accidentally send commands that were intended for a different mode. this could be addressed by all 3 modes sharing the same command space (but this limits the number of commands available).

**Comment by kfirmanty** [comment]
I already proved that my assumptions are wrong so I might not be best fitted to answer that question but from my perspective:
* using different addresses:
   `+` multiple W/ even in same mode can be addressed separately - for example one W/ in synth mode could be used as bass voice - second one as solo (this split might require additional ops in teletype to select "current" i2c address to which commands are sent AFAIK)
   `-` uses up address space
* using same address, but different command ids for different modes
    `+` only one address is being used
    `-` can introduce conflicts in command space
    `-` sending separate commands to multiple W/ modules in same mode won't be possible

**Comment by trentgill** [comment]
I'm treating the crow descriptor files as my reference (I build the crow `ii` files before I implement the features), so they are my 'these are the addresses & commands' catalogue.

Mannequins addresses at present:
- 0x70 Just Friends (default)
- 0x71 W/Tape (default)
- 0x72 W/Tape (alt)
- 0x73 Reserved
- 0x74 Reserved
- 0x75 Just Friends (alt)
- 0x76 W/Syn (default)
- 0x77 W/Syn (alt)
- 0x78 W/Delay (default)
- 0x79 W/Delay (alt)

0x73 & 0x74 were intended for W/ but will likely be unused if they are needed by another device (though I believe there's still plenty of unused addresses.

I chose to use separate addresses without too much thought. Ansible did it, so I copied that. It made sense to me because I imagine people are more likely to have multiple W/ modules set to different modes than all in the same mode. I can see the benefit of putting them all on the same address, then building some kind of ii-address-selector startup thing for W/ but I haven't done that yet. Doing so would increase the bar of what's possible (6 of the same mode), while making the setup more complex (one more setup mode to learn about).

I guess the main reason is it fits the model of crow's `ii` descriptors. It makes sense that each mode should have it's own namespace. Additionally, the stm32 chip I'm using allows dual addresses, so adding 'global' commands is possible in that way. I was considering that 0x71 (the first W/Tape address) could potentially be forwarded to all W/ devices (regardless mode).

I've typed too much! Basically I *could* change it, but would need a strong push in that direction to carve out the time to do that.

**Comment by tehn** [comment]
i am happy to change ansible's address consumption for an alternative proposal!

**Comment by scanner-darkly** [comment]
i don't think we need to change it (it would require a corresponding change in teletype and would make it not backwards compatible), and sorry, didn't mean to suggest we need to change anything for w/ implementation - was curious about the chosen approach as there are multiple aspects to consider and i thought maybe i was missing some!

teletype perspective on this: i really like the fact that ansible in tt expander mode can be addressed by using the same `CV` and `TR` ops, or that you can address multiple er-301 or telexo in the same manner (`SC.CV` 1-100 will get send to 1st unit, 101-200 to 2nd etc). this makes it easy to use them in a loop, say, i could reset all of them with one line `L 1 300: SC.CV I 0`.

for some devices we went with selecting the unit you're addressing - this is more useful for ops that don't take an index. i did the same for disting ex, but in use i found it got pretty annoying/confusing when you mostly address one unit, but once in a while you want to address another one, which would result in code like `EX 2; EX.NOTE x y; EX 1;` - okayish for 1 line, but if you need to add another one you have to repeat it, and if you forget to set the current unit to the main one, it creates an issue that sometimes not obviously clear. the way i solved it was adding modifiers: `EX3: this line only gets sent to unit 3`.

i really like the idea of not having to remember to do unit switching if your units are in different modes. but i guess you still have to do it if you want to support multiple modules with the same mode.

**Pull request merged**
