### PR TITLE
refactor i2c

### PR DESCRIPTION
**Pull request by scanner-darkly**
- fixed addresses (addresses are 7 bit, not 8 bit, cleared MSB)
- split commands
- added comments / reformatted

see https://llllllll.co/t/teletype-i2c-protocol/13642 for discussion

### CODE REVIEW

**Comment by scanner-darkly** [comment]
that would mean newer versions of teletype wouldn't be backwards compatible and would require updating all the other firmwares as well - perhaps more trouble than it's worth?

**Comment by tehn** [comment]
oy if course you’re correct!

**Comment by trentgill** [comment]
I believe 'only even addresses' was because we thought it was left-aligned 7bit number?
Regardless this seems like a positive change as it won't break anything, and means the code reflects what is happening on a hardware level.
I will update the JF & W/ repos which will make those defines a lot more meaningful!

**Comment by bpcmusic** [comment]
Thanks for taking the lead on this, @scanner-darkly. You really are the best!

It looks like we need to add in the range for the TELEX modules (0x60-0x6F), fix the conflict with the 16n (FADER), fix the conflict with the ER-301, and add in the tentative addresses for the Tetrapad integration that I've proposed in specification with kisielk. I'll suggest some things over on the forum shortly.

**Comment by scanner-darkly** [comment]
@bpcmusic - sorry, should've tagged you in this PR! i'll do another commit to include your changes.

**Comment by scanner-darkly** [comment]
@bpcmusic added your changes, i expanded the names to avoid potential conflicts, let me know if they look okay. er-301 change will be in a separate PR.

**Comment by scanner-darkly** [comment]
@bpcmusic @tehn are we good to merge this?

**Comment by bpcmusic** [comment]
I'll test tomorrow with the latest; apologies for not responding sooner. I've been in SMD hell this weekend and am still half-delirious from the fumes. Thx@

**Comment by scanner-darkly** [comment]
@bpcmusic no worries, i need to do another pull request for the er-301 changes and figured i could just add any other required changes there. would you need an updated teletype firmware for testing? i’ll update my tt branch to use this version tomorrow.

**Pull request merged**
