### PR TITLE
update libavr32 random number generator

### PR DESCRIPTION
**Pull request by alpha-cactus**
this pull request is to update the algorithm used by the `random.c/h`. this is needed for the seed ops pull request for teletype.
https://github.com/monome/teletype/pull/176

basically the old algorithm was using a linear congruential generator which resulted in the lower bits to not be very random.  new algorithm is a multiply with carry prng.  I also removed the min/max range mod from the `random_next` function as the teletype op firmware already handles range limiting.

I did a search to see if any other firmware was using this generator.  as far as I could tell only `arp.c` (used by ansible) uses it.  a very slight modification to `arp.c` was needed since I removed the range modulus from the algorithm. I tried to update the unit tests in `libavr32/test/unit`, but received the following make error both before and after modification. maybe @ngwese can help with this, and hopefully also give input on these changes.

```
alphacactus:test ryanhodgman$ make
LN      > build/unit/test_arp.out
Undefined symbols for architecture x86_64:
  "_irqs_pause", referenced from:
      _arp_seq_set_state in test_arp.o
  "_irqs_resume", referenced from:
      _arp_seq_set_state in test_arp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [build/unit/test_arp.out] Error 1
```

### CODE REVIEW

**Comment by scanner-darkly** [comment]
try adding the following to `test\include\conf_tc_irq.h` and see if that fixes the tests:
```
u8 irqs_pause(void) { return 0; }
void irqs_resume(u8 irq_flags) {}
```

**Comment by alpha-cactus** [comment]
nope didn't work.  I'll continue to investigate. sorry for the late response I'm in the process of moving this week.

**Comment by scanner-darkly** [comment]
sorry for the delay! to fix the issue with tests add this to `unit\est_arp.c`: (same thing as i posted above)
```
u8 irqs_pause(void) { return 0; }
void irqs_resume(u8 irq_flags) {}
```

**Comment by alpha-cactus** [comment]
great just pushed that change.

> Sorry. Didn’t seem the notification until just not. This made me realize that fixed the test breakage in a branch I haven’t pushed up. I’ll look at the changes as soon as I get to something which isn’t a phone.

thanks for taking a look!

**Pull request merged**
