### PR TITLE
added ops KR.TOG, KR.CLK

### PR DESCRIPTION
**Pull request by AaronMeyers**
KR.TOG toggles the mute state of a track in Kria
KR.CLK clocks a track in Kria when it has TT manual clocking on

### CODE REVIEW

**Comment by tehn** [comment]
can you explain `KR.TOG`? i'm confused because we already have `KR.MUTE`

also i'm not sure what TT manual clocking means-- did you intend to have another command to disable the internal clock? or does it just add clock pulses? (ie, you disable the internal clock by using a jack in the front panel?)

**Comment by AaronMeyers** [comment]
KR.TOG just flips the current state of tracks muting... the only argument it takes is which track you want to toggle. KR.MUTE takes a track number and an argument for whether its muted (1) or unmuted (0). So KR.TOG is not strictly necessary, more of a convenience function.

KR.CLK is so that you can use individual clocks with Kria tracks via teletype. At the moment, I added toggle buttons in the upper left corner of the scale screen, but it might be better elsewhere or done with an OP to enable/disable teletype clocking... I wanted to get your input first.

When a track has teletype clocking enabled, it stops responding to the main clock (whether its the internal one or coming in from the clock input on the front panel). That track will only advance steps when KR.CLK is called, specifying that track as the argument.

**Comment by tehn** [comment]
understood. so kria interface manages the kria clock, that's cool/fine.

can you rename `KR.TOG` to something more meaningful like `KR.TMUTE` or `KR.MUTE.TOG`?

**Comment by AaronMeyers** [comment]
sounds good. will change it to KR.TMUTE and resubmit.

**Comment by tehn** [comment]
the travis build is failing but i expect it'll be fine-- other modules are locked to specific libavr32 versions

**Comment by AaronMeyers** [comment]
cool... i will go ahead and submit a pull request for the teletype repo now.

**Pull request merged**
