### PR TITLE
stability improvements

### PR DESCRIPTION
**Pull request by scanner-darkly**
stability improvements:
- trigger priority lowered to 1
- i2c speed lowered to 100000
- SPI updates are protected from interrupts
- event variables are now `volatile`
- more granular interrupt masking

other changes:
- added a function to get tcTicks value

the main idea is to protect critical code and variables (timers and events) by masking interrupts where applicable. i've also updated `timers_pause` and `timers_resume` methods to be more granular (only mask those interrupts that haven't been masked yet), and this way they restore masking to exactly what it was before (so it should handle the case of a trigger ISR getting interrupted by a timer ISR, for instance). all SPI code is now protected by the new irq masking functions as well to make sure a screen refresh does not interfere with a CV update, for instance. 

i've also lowered the UI (trigger) priority level so that it does not interfere with i2c (which is level 3) - i have a feeling i2c code does not handle being interrupted well.

@tehn @samdoshi @ngwese please take a look. thanks!

### CODE REVIEW

**Comment by scanner-darkly** [comment]
not sure why travis CI failed... perhaps because it's a breaking change for any firmware that uses libavr32?

**Comment by samdoshi** [comment]
I think most of them are due to extra `c` files needing to be added to `config.mk`, plus a few issues with changed names. I'd suggest going through each one and satisfying yourself that there are no issues more serious than that.

I will try to have a proper look at the PR later this week.

**Comment by scanner-darkly** [comment]
yeah, looks like just need to update `config.mk`, no other errors.

**Comment by tehn** [comment]
i'll pull now and fix everything

**Pull request merged**
