### PR TITLE
LV CV and CY CV remotes

### PR DESCRIPTION
**Pull request by scanner-darkly**
preparation for new LV CV and CY CV remote commands for ansible

### CODE REVIEW

**Comment by scanner-darkly** [comment]
@tehn please take a look

**Comment by tehn** [comment]
can you describe what these commands will do? CV is pretty vague so it
wasn't immediately clear to me.

**Comment by scanner-darkly** [comment]
sorry - should've included it in the pull request. the main idea is to be able to read the current CV value being output by Levels or Cycles. 

for Levels `set` could also be implemented, so you could set current CV  values as well - in conjunction with `LV.POS` this would allow to populate Levels from TT patterns and vice versa, for instance. for Cycles `set` probably doesn't make sense since you would want to set the position instead, which is already available.

**Comment by scanner-darkly** [comment]
one more thing - i thought of re-using the existing `CV` commands which would have the benefit of not having to modify TT scripts even if you switch apps on ansible, but it's not possible since Levels and Cycles use a different i2c address.

**Comment by tehn** [comment]
got it. i think reading the current CV outputs makes sense.

set on Levels isn't a perfect use case, however. not without being able to
switch patterns, and these get into weird UI-remote-control that needs to
be better thought out. reading CV would be "what is the CV output
currently" whereas setting CV doesn't have a clear analogy. whereas
something like set-pattern would be agnostic to the current CV setting, or
current pattern.

so let's keep these CV commands to read only for now. unless you have a
counter proposal of course.

b

**Comment by scanner-darkly** [comment]
@tehn makes sense! 
should have the corresponding ansible/teletype pull requests next week.

**Pull request merged**
