### PR TITLE
ii messages for new ansible remote ops

### PR DESCRIPTION
**Pull request by csboling**
Adds ii message types for supporting the following Teletype remote ops for Ansible (discussion starts [here](https://llllllll.co/t/teletype-3-feature-requests-and-discussion/16219/291)). Binaries with these ops working are [here](https://llllllll.co/t/ansible-earthsea/6891/507). Will follow up with Teletype and Ansible merges after this is merged so I can fix up the submodule references.

```
ANS.G x y / ANS.G x y z   # get/set grid key state (z) at pos x, y
ANS.G.P x y               # simulate grid key press (down + up) on ansible at pos x, y
ANS.G.LED x y             # get grid LED state for key x, y
ANS.A n d                 # simulate arc encoder rotation of ring n, delta d
ANS.A.LED n x             # get arc LED state for ring n, LED x (clockwise from north)
KR.PG / KR.PG x           # get/set active kria page
KR.CUE / KR.CUE x         # get/set cued pattern
KR.DIR n / KR.DIR n x     # get/set step direction for track n to direction 0-4
```

### CODE REVIEW

**Comment by scanner-darkly** [comment]
looks like false travis build failure, not sure if there is a way to re-run other than committing some white space change or something?

**Comment by scanner-darkly** [comment]
looks like this fixed it! 
@tehn - does this conflict with any of the crow addresses?

**Comment by csboling** [comment]
@scanner-darkly no I2C addresses were added, just new message codes for existing addresses used by Ansible.

**Comment by csboling** [comment]
Does this still need any changes to be merged? After this goes in I can make dependent PRs for Ansible and Teletype for these remote features.

**Pull request merged**
