### PR TITLE
change terminology in public i2c API

### PR DESCRIPTION
**Pull request by csboling**
There are a bunch of others in internal ASF libraries but I think this is everything that gets used in downstream code bases.

### CODE REVIEW

**Comment by csboling** [comment]
Hm yeah, this'll definitely fail the travis build since it tries to confirm that downstream repos build OK. I did confirm that I can build Ansible and TT off this libavr32 branch though.

**Comment by scanner-darkly** [comment]
awesome!

almost did it today but got tied up renaming branches in my repos.
the builds are probably failing because some functions are called from teletype/ansible code?

**Comment by csboling** [comment]
Right, bit of a chicken-and-egg thing where I think this would need to get merged first to patch the other repos.

**Comment by tehn** [comment]
yep, chicken and egg!

**Pull request merged**
